language: go
go:
- 1.x
services:
- mongodb
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_f9907a2bc3a1_key -iv $encrypted_f9907a2bc3a1_iv -in deploy_key.enc -out ./deploy_key -d
- docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
- docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
- docker-compose -f docker-compose.yml -f docker-compose.prod.yml push
git:
  depth: 3
deploy:
  provider: script
  skip_cleanup: true
  script: chmod 600 deploy_key && ssh -o StrictHostKeyChecking=no -i deploy_key root@104.131.43.177
    ./deploy.sh
  on:
    branch: master
env:
  global:
  - secure: dI2C37gPjiQf2zksvPUOxRLWW1eSSsVcPvKBkkvbeLp/i3qMvqCnBAIDc/C71FsrdfK8fWlbcvyu/BT6vFBsUE017Kp2sNMMp/J6G7HKkjxVjPSO3+b1zEdeSKfM/iXYed8qhbD+ZOYG8FhAkxq6pQvTLs6QitHAoSjcMJvOExL9A4gm6mcPqdvCGIkFK1BToq1jrjGglvUPgl8qz79ogAqWYArBAOW9QKaY/OvE4Lbd5I1Nqg8kj5Qq2pVnnAx+CUegwjZ5RGLB605lXqyEdGUYQxZ8bMvC0An+t8FeHCmAYnXC26o401RpC3mqhFYO/XC8ZGk3QcuNJvTMVBeI5z8onqEmey4Z9hGSfH4/Zfmq8KD37be8H+tSgQ3J4N5rxd+sV1XivzdXbKNe3hX/gTsOFJ9fFsbjhYrD9mgkYU1NLmOQ2k+2cW9X7Zw2MIkf4fI/mwOhROAkl3vCyzyo4Mxs4Ba9vlHudsq8a2gC6kuwNXF7hjrfeS+/c4D21YfWV2b6C7s8wqv4gge/Mvususf61JFosD0paGQasMKV1m0waQ17nlY9qBEKks2rGLEu8r+Tl4h8B0gAAvt1EPxpI+sAenVyAAIV3biNjywiuQmi8qEz65q5q4q4K6DjXZimseH3Zw3Yp7zUoLgEM+SmZbLNrm/q9lH9P3Q9fmlMPQU=
  - secure: WPzIGl1wpmcxue91IjDgtuYifD/JJO/g+Hmn8/+AufPjU6UIBPl2KJ2XOMa9k+qulMCE8LpBSCFc6KuqHqKxvEgmi3bbQrnqw7kV0O+aB45cEnNtP3BPtDRd4BEcP4tgssakkJtKAnz2Pbs2vduacSF7cQJy0c2U3nHFhJZu+a1D5DfeEALmWus8v2OrXw6kkoNM4cib124Aadz5cM556smSXcz9s04AATdDlCMXJODyVgPAeyELElg1lI8Nvgg5xmiBpJrz8BfNykM2z2/vhPP1KS58EyQsCgY6DQ7jMVnJcBCr0iXYZxPGyyYct9yC/Q54Qnb45eSOduSMb14rr2/KLqX6JvG+3MUa8R/NfxWk1or1wglhzn3jBYR8cEvEvKpsIFeY8WL8O1DzFtOvNlFrYXlb6dMrzJ9v/Kg58OHvYNgIOhDwUjDsSrN5LoW6tfMmr3YXKyq9fPhveumXMn3hzFxw9n57Nwx5UyjYNnXZWrUu/mdOcYWNsrOzy2q52UMQXUKEcUhxrewB7b6GxnIBs3dhdo9Ua5KZtuaq4JHmj5KPgYIziSbONPjjZ8rj1QSpm4jZVK44nGqqSY0fYnEFBntBhJTjEQThxmPEn00NNkwt9cJCuUMj+Jrovc5Jj+mlA3r0IGz9TqefP1CxZXruEP3P2c0tB0womhvFL7w=
