language: go
go:
- 1.x
services:
- mongodb
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_f9907a2bc3a1_key -iv $encrypted_f9907a2bc3a1_iv
  -in deploy_key.enc -out ./deploy_key -d
- docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
- docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
- docker-compose -f docker-compose.yml -f docker-compose.prod.yml push
git:
  depth: 3
deploy:
  provider: script
  skip_cleanup: true
  script: chmod 600 deploy_key && ssh -v -o StrictHostKeyChecking=no -i deploy_key
    root@104.131.43.177 ./deploy.sh
  on:
    branch: master
env:
  global:
  - secure: rbmke7VgjnP+AwWn96iKi0Fd1GId/tKGb19agMYC5NzwmHg6Yi8DJ5giSPcDL/X0yoEn5oP8ck2Pkf6mxUY6MAY0wA5luq7LDtWGx/X7fhG3biPF6ZmogLVNI7VF1qDw0Hr2qsYwEXTmyTeapQvKKtN4sm/QaiLCEkARqYScHHDravj/DIn+fW8OoZWXNysZAqdpCTYT7apVqlXiIJ/Dll8e+AFrPYVZ2vHyejoC9OGmTALpSVhIZ18xwp0zH9KhcYZeUAdLW9o7MWbJB0mqxuqQ1mpOOhhHvOEI19hioi2Mswn9SLHO28XKRb/5VQB20NaB3nnzWBBAtSUlgoB/opgEQUabzfjGB7z9LCVgCuOuvZb/cikpaVUGzD3PL87DQw6LfmOfxk+tifcaRhaYzkKLF+5MTWo1sblBQXCvffVMS+Fn8B2S21MfDYciedvhDyJczw3yaW8fwhSos7rQlZM5mvI03mpOVfuFNQK+bZH/x4/yMu3hBGlj/5K9jzkE9qrFB+pcG4+3/xGBtDLav2MR8YfI/+j04wJW0jUa8MO2ZnFKBwqzRGxPVtpUgldWA//kXpQ84RqCHTYmGkqDOCcImoSgHAYU18iRplxWgkug+ZJzIqBluTqUHI6FSLsbXcf3Y6X3EzPz4LTxzn9plpFDsiqKLCBqFf3MUJ0W/lE=
  - secure: Bd6hlmqJxtFrjQUJRiTbZXlHT4I2jGq/zWvf7+muBbDluHr5X2au3c1F0pUU/cthuCJD0aufxW3vjBK2dkBzmfuGlHhen4gsv6uIOAIbgG8cHWXLH9rh2LksqmgxjB59aSBsVExrWPE6KviMQSdkp+CfEGA1THRSdhj+Qa+3RxHNuJua3wbUa7ieiOU1lwWPvSOKGnL2md9SMI6YZ96qsHutHExPr/QbWxzQ9D8jd1YLCjdPdnHe2WqNBfGpgbRNXYdC63DmhZyHb8vSphKs6rB2m78UrIW5v1mVud/c3VeUTeo/1Y7Q7BDVkBieIBxNjoGUu/PdejLYjA/cSx4EvNM1ZW36+D3VxoX94sz+yZMHuztCzpU/zMpS30xZiHbwa+My9/8E95YnDPfi9Xw8HskWW/18iDmZDRU1OdG+UuqPzK7b5UA3W96aPx2Qvye3ZpzwlkOPnqXQmmwXrrCOlLXlcDWJvtbXNG6E+/dr+pcPv1OmnZBKzA41AvFaGFXMDesdz8SK6oOw5DBdWDXiOCYuL2Yw1xfCJxUv+XUiGY/JFbuZ+xk0MwZsGRReaWnBfKP2aRslMad0tqWKKbNx0yaSDyy994F7Xx6jqJdIQ5sj5J5gwOw3ekKjS8O4AxLSMNeOAziAd9DJuMOBFjgPqEivLim7ikDbyX9GDAAjf5U=
