# default docker-compose config
# for running a 'dev' deployment of shelves-server
version: '3'
services:
  gateway:
    build: gateway/
    image: kexpcapstone/gatewaysvc
    environment:
      - SHELVESSVCADDR=shelves:80
      - LIBRARYSVCADDR=library:80
      - TLSCERT=/tls/fullchain.pem
      - TLSKEY=/tls/privkey.pem
      - DBADDR=mongodb:27017
      - REDISADDR=redissvr:6379
      - SESSIONKEY=blackcoffee
    ports:
      - "443:443"
    volumes:
      - ./tls:/tls:ro
    container_name: gateway
    networks:
      - dylan
  mongodb:
    image: "mongo"
    container_name: mongodb # to be changed if needed
    networks:
      - dylan
  mongo-seed:
    image: "mongo"
    container_name: mongo-seed
    links:
      - mongodb
    volumes:
      - ./data:/data/seeds
    command:
      'bash -c "mongoimport --host mongodb --db library --collection releases --type json -v --file /data/seeds/dalet_deploy.json --jsonArray"'
    networks:
      - dylan
  redissvr:
    image: "redis"
    container_name: redissvr
    networks:
      - dylan
  library:
    build: library/
    image: kexpcapstone/librarysvc
    container_name: library
    environment:
      - DBADDR=mongodb:27017
      - RELEASEDB=library
      - RELEASECOLL=releases
      - ARTISTCOLL=artists
      - GENRECOLL=genres
    networks:
      - dylan
  shelves:
    build: shelves/
    image: kexpcapstone/shelvessvc
    container_name: shelves
    environment:
      - DBADDR=mongodb:27017
    networks:
      - dylan
networks:
  dylan:
