# default docker-compose config
# for running a 'dev' deployment of shelves-server
version: '3'
services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    image: kexpcapstone/gatewaysvc
    environment:
      - SHELVESSVCADDR=shelves:80
      - LIBRARYSVCADDR=library:80
      - TLSCERT=/tls/fullchain.pem
      - TLSKEY=/tls/privkey.pem
      - DBADDR=mongodb:27017
      - REDISADDR=redissvr:6379
      - SESSIONKEY=blackcoffee
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./tls:/tls:ro
    container_name: gateway
    networks:
      - dylan
  mongodb:
    image: "mongo"
    container_name: mongodb # to be changed if needed
    networks:
      - dylan
  mongo-seed:
    image: "mongo"
    container_name: mongo-seed
    links:
      - mongodb
    volumes:
      - ./data:/data/seeds
      - ./mongo-seed.sh:/usr/local/bin/mongo-seed.sh
    command:
      - mongo-seed.sh
    networks:
      - dylan
  redissvr:
    image: "redis"
    container_name: redissvr
    networks:
      - dylan
  library:
    build:
      context: .
      dockerfile: library/Dockerfile
    image: kexpcapstone/librarysvc
    container_name: library
    environment:
      - DBADDR=mongodb:27017
      - RELEASEDB=library
      - RELEASECOLL=releases
      - ARTISTCOLL=artists
      - GENRECOLL=genres
      - NOTECOLL=notes
    networks:
      - dylan
  shelves:
    build:
      context: .
      dockerfile: shelves/Dockerfile
    image: kexpcapstone/shelvessvc
    container_name: shelves
    environment:
      - DBADDR=mongodb:27017
      - SHELVESDB=shelves
      - SHELVESCOLL=shelves
    networks:
      - dylan
networks:
  dylan:
