# default docker-compose config
# for running a 'dev' deployment of shelves-server
version: '3'
services:
  gateway:
    image: kexpcapstone/gatewaysvc:prod
    environment:
      - SHELVESSVCADDR=shelves:80
      - LIBRARYSVCADDR=library:80
      - TLSCERT=/tls/live/api.kexpshelves.com/fullchain.pem
      - TLSKEY=/tls/live/api.kexpshelves.com/privkey.pem
      - DBADDR=mongodb:27017
      - REDISADDR=redissvr:6379
      - SESSIONKEY=blackcoffee
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /etc/letsencrypt:/tls:ro
    container_name: gateway
  mongodb:
    image: "mongo"
    container_name: mongodb # to be changed if needed
    networks:
      - dylan
  mongo-seed:
    image: "mongo"
    container_name: mongo-seed
    links:
      - mongodb
    volumes:
      - /srv/data:/data/seeds # data for populating release library
      - /root/mongo-seed.sh:/usr/local/bin/mongo-seed.sh
    command:
      - mongo-seed.sh
    networks:
      - dylan
  redissvr:
    image: "redis"
    container_name: redissvr
  library:
    image: kexpcapstone/librarysvc:prod
    container_name: library
    environment:
      - DBADDR=mongodb:27017
      - RELEASEDB=library
      - RELEASECOLL=releases
      - ARTISTCOLL=artists
      - GENRECOLL=genres
  shelves:
    image: kexpcapstone/shelvessvc:prod
    container_name: shelves
    environment:
      - DBADDR=mongodb:27017
networks:
  default:
    external:
      name: dylan
